/**
 * publish-r2.js — push the bento CODE/DESIGN sources to R2 (editor/ prefix).
 *
 * WHY: live fear pages are composed by the Worker via composeFearPage(), which
 * reads includes/template/styles from R2 FIRST (editor/...) and only falls back
 * to the deployed /editor-src assets. That means editing a file in bento/ and
 * running `wrangler deploy` is NOT enough — R2 shadows the deploy. This script
 * makes the repo the source of truth by syncing the code files into R2 on every
 * deploy, so what you build is always what goes live.
 *
 * SAFE BY DESIGN: it only pushes code/design files (template, body template,
 * shared CSS, includes, manifest, phobias). It NEVER touches pages/* (copy.json,
 * body.html, page.json) or site-img/* — so any live content/photo edits made in
 * the /editor tool are preserved.
 *
 * Usage: node scripts/publish-r2.js
 */
const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const BENTO = path.join(ROOT, 'bento');
const INC = path.join(BENTO, 'newincludes');
const PUBLIC = path.join(ROOT, 'public');

const BUCKET = 'phobiafree-chat-files';
const PREFIX = 'editor/';

function contentType(file) {
  if (file.endsWith('.css')) return 'text/css; charset=utf-8';
  if (file.endsWith('.json')) return 'application/json';
  return 'text/html; charset=utf-8';
}

function put(key, file) {
  const target = `${BUCKET}/${PREFIX}${key}`;
  execSync(
    `npx wrangler r2 object put "${target}" --file "${file}" --content-type "${contentType(file)}" --remote`,
    { stdio: 'pipe' }
  );
  console.log('  +', PREFIX + key);
}

function main() {
  const files = [];

  const addIfExists = (key, file) => {
    if (fs.existsSync(file)) files.push([key, file]);
  };

  addIfExists('template.html', path.join(BENTO, 'template.html'));
  addIfExists('body.template.html', path.join(BENTO, 'body.template.html'));
  addIfExists('styles.css', path.join(BENTO, 'styles.css'));
  addIfExists('phobias.json', path.join(BENTO, 'phobias.json'));
  // manifest is generated by publish-editor-src.js into public/editor-src/
  addIfExists('manifest.json', path.join(PUBLIC, 'editor-src', 'manifest.json'));

  if (fs.existsSync(INC)) {
    for (const f of fs.readdirSync(INC)) {
      if (f.endsWith('.html')) files.push(['includes/' + f, path.join(INC, f)]);
    }
  }

  if (!files.length) {
    console.error('publish-r2: nothing to publish (bento/ not found?)');
    process.exit(1);
  }

  console.log(`publish-r2: syncing ${files.length} code files to R2 ${PREFIX} (pages/content untouched) ...`);
  for (const [key, file] of files) put(key, file);
  console.log('done');
}

main();
